version: '3.8'
services:
  nginx:
    image: nginx
    restart: always
    container_name: reverse-proxy
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - db
      - web
    ports:
      - "8020:8020"
    networks: 
      - products
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: complexpassword
    volumes:
      - ./tmp:/var/lib/mysql
    expose: 
      - "3306"
    networks: 
      - products
  web:
    build: ./Shopping-App-IRIS
    environment: 
      DATABASE_HOST: db
      DB_PASSWORD: complexpassword
    expose:
      - "3000"
    links:
      - db
    networks: 
      - products
    tty: true
networks: 
  products: